version: "3.7"
services:
  client:
    restart: always
    build: client/
    depends_on:
      - server
    ports:
      - "3000:3000"
  server:
    restart: always
    build: server/
    ports:
      - "8000:8000"